<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Tests\Fixer\Phpdoc;

use PhpCsFixer\Tests\Test\AbstractFixerTestCase;

/**
 * @internal
 *
 * @covers \PhpCsFixer\Fixer\Phpdoc\PhpdocNullableTypeDeclarationFixer
 *
 * @extends AbstractFixerTestCase<\PhpCsFixer\Fixer\Phpdoc\PhpdocNullableTypeDeclarationFixer>
 *
 * @phpstan-import-type _AutogeneratedInputConfiguration from \PhpCsFixer\Fixer\Phpdoc\PhpdocNullableTypeDeclarationFixer
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class PhpdocNullableTypeDeclarationFixerTest extends AbstractFixerTestCase
{
    /**
     * @param _AutogeneratedInputConfiguration $configuration
     *
     * @dataProvider provideFixCases
     */
    public function testFix(string $expected, ?string $input = null, array $configuration = []): void
    {
        $this->fixer->configure($configuration);
        $this->doTest($expected, $input);
    }

    /**
     * @return iterable<string, array{0: string, 1?: null|string, 2?: _AutogeneratedInputConfiguration}>
     */
    public static function provideFixCases(): iterable
    {
        // Default syntax: question_mark
        yield 'null|Type to ?Type - simple scalar' => [
            '<?php /** @var ?int $value */',
            '<?php /** @var null|int $value */',
        ];

        yield 'Type|null to ?Type - simple scalar' => [
            '<?php /** @var ?int $value */',
            '<?php /** @var int|null $value */',
        ];

        yield 'null|Type to ?Type - class' => [
            '<?php /** @var ?\stdClass $obj */',
            '<?php /** @var null|\stdClass $obj */',
        ];

        yield 'null|Type to ?Type - fully qualified class' => [
            '<?php /** @var ?\Foo\Bar\Baz $obj */',
            '<?php /** @var null|\Foo\Bar\Baz $obj */',
        ];

        yield '@param tag' => [
            '<?php /** @param ?string $value */',
            '<?php /** @param null|string $value */',
        ];

        yield '@return tag' => [
            '<?php /** @return ?int */',
            '<?php /** @return null|int */',
        ];

        yield '@property tag' => [
            '<?php /** @property ?string $name */',
            '<?php /** @property null|string $name */',
        ];

        yield '@property-read tag' => [
            '<?php /** @property-read ?int $count */',
            '<?php /** @property-read null|int $count */',
        ];

        yield '@property-write tag' => [
            '<?php /** @property-write ?array $items */',
            '<?php /** @property-write null|array $items */',
        ];

        yield '@throws tag' => [
            '<?php /** @throws ?\Exception */',
            '<?php /** @throws null|\Exception */',
        ];

        yield 'generic type' => [
            '<?php /** @var ?iterable<\SplFileInfo> */',
            '<?php /** @var null|iterable<\SplFileInfo> */',
        ];

        yield 'nested generic type' => [
            '<?php /** @var ?array<string, array<int, \Foo>> */',
            '<?php /** @var null|array<string, array<int, \Foo>> */',
        ];

        yield 'nullable type inside generic' => [
            '<?php /** @var array<?string> */',
            '<?php /** @var array<null|string> */',
        ];

        yield 'nullable type inside nested generic' => [
            '<?php /** @var array<int, array<?string>> */',
            '<?php /** @var array<int, array<null|string>> */',
        ];

        yield 'multiple nullable types in generic' => [
            '<?php /** @var array<?int, ?string> */',
            '<?php /** @var array<null|int, null|string> */',
        ];

        yield 'skip already fixed' => [
            '<?php /** @var ?int $value */',
        ];

        yield 'skip multi-type union' => [
            '<?php /** @var null|int|string $value */',
        ];

        yield 'skip non-nullable type' => [
            '<?php /** @var int|string $value */',
        ];

        yield 'skip standalone null' => [
            '<?php /** @var null $value */',
        ];

        yield 'skip DNF type with null' => [
            '<?php /** @var (A&B)|null $value */',
        ];

        yield 'NULL uppercase' => [
            '<?php /** @var ?int $value */',
            '<?php /** @var NULL|int $value */',
        ];

        yield 'multiline docblock' => [
            <<<'PHP'
                <?php
                /**
                 * @param ?int $value
                 * @return ?string
                 */
                PHP,
            <<<'PHP'
                <?php
                /**
                 * @param null|int $value
                 * @return null|string
                 */
                PHP,
        ];

        yield '@method tag' => [
            '<?php /** @method ?int getValue() */',
            '<?php /** @method null|int getValue() */',
        ];

        yield 'callable with nullable param' => [
            '<?php /** @var callable(?string): void */',
            '<?php /** @var callable(null|string): void */',
        ];

        yield 'callable with nullable return using question mark' => [
            '<?php /** @var callable(string): ?int */',
        ];

        yield 'Closure type' => [
            '<?php /** @var ?\Closure */',
            '<?php /** @var null|\Closure */',
        ];

        // Union syntax configuration
        yield '?Type to null|Type - simple scalar' => [
            '<?php /** @var null|int $value */',
            '<?php /** @var ?int $value */',
            ['syntax' => 'union'],
        ];

        yield '?Type to null|Type - class' => [
            '<?php /** @var null|\stdClass $obj */',
            '<?php /** @var ?\stdClass $obj */',
            ['syntax' => 'union'],
        ];

        yield '?Type to null|Type - fully qualified class' => [
            '<?php /** @var null|\Foo\Bar\Baz $obj */',
            '<?php /** @var ?\Foo\Bar\Baz $obj */',
            ['syntax' => 'union'],
        ];

        yield '@param tag with union syntax' => [
            '<?php /** @param null|string $value */',
            '<?php /** @param ?string $value */',
            ['syntax' => 'union'],
        ];

        yield '@return tag with union syntax' => [
            '<?php /** @return null|int */',
            '<?php /** @return ?int */',
            ['syntax' => 'union'],
        ];

        yield 'generic type with union syntax' => [
            '<?php /** @var null|iterable<\SplFileInfo> */',
            '<?php /** @var ?iterable<\SplFileInfo> */',
            ['syntax' => 'union'],
        ];

        yield 'nullable type inside generic with union syntax' => [
            '<?php /** @var array<null|string> */',
            '<?php /** @var array<?string> */',
            ['syntax' => 'union'],
        ];

        yield 'nested nullable types with union syntax' => [
            '<?php /** @var array<int, array<null|string>> */',
            '<?php /** @var array<int, array<?string>> */',
            ['syntax' => 'union'],
        ];

        yield 'skip already union syntax' => [
            '<?php /** @var null|int $value */',
            null,
            ['syntax' => 'union'],
        ];

        yield 'multiline docblock with union syntax' => [
            <<<'PHP'
                <?php
                /**
                 * @param null|int $value
                 * @return null|string
                 */
                PHP,
            <<<'PHP'
                <?php
                /**
                 * @param ?int $value
                 * @return ?string
                 */
                PHP,
            ['syntax' => 'union'],
        ];

        yield 'callable with nullable param union syntax' => [
            '<?php /** @var callable(null|string): void */',
            '<?php /** @var callable(?string): void */',
            ['syntax' => 'union'],
        ];

        yield 'callable with nullable return union syntax' => [
            '<?php /** @var callable(string): null|int */',
            null,
            ['syntax' => 'union'],
        ];

        yield 'array shape with nullable value' => [
            '<?php /** @var array{name: ?string, count: ?int} */',
            '<?php /** @var array{name: null|string, count: null|int} */',
        ];

        yield 'array shape with nullable value union syntax' => [
            '<?php /** @var array{name: null|string, count: null|int} */',
            '<?php /** @var array{name: ?string, count: ?int} */',
            ['syntax' => 'union'],
        ];

        yield 'conditional type is preserved' => [
            '<?php /** @return ($value is null ? null : string) */',
        ];

        yield 'class constant reference is preserved' => [
            '<?php /** @var Foo::BAR|null $value */',
        ];

        yield 'class constant reference with null first' => [
            '<?php /** @var null|Foo::BAR $value */',
        ];
    }
}

