<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Fixer\Phpdoc;

use PhpCsFixer\AbstractFixer;
use PhpCsFixer\DocBlock\Annotation;
use PhpCsFixer\DocBlock\DocBlock;
use PhpCsFixer\DocBlock\TypeExpression;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\ConfigurableFixerTrait;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
use PhpCsFixer\Preg;
use PhpCsFixer\Tokenizer\Token;
use PhpCsFixer\Tokenizer\Tokens;

/**
 * @phpstan-type _AutogeneratedInputConfiguration array{
 *  syntax?: 'question_mark'|'union',
 * }
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 *  syntax: 'question_mark'|'union',
 * }
 *
 * @implements ConfigurableFixerInterface<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration>
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class PhpdocNullableTypeDeclarationFixer extends AbstractFixer implements ConfigurableFixerInterface
{
    /** @use ConfigurableFixerTrait<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration> */
    use ConfigurableFixerTrait;

    private const OPTION_SYNTAX_UNION = 'union';
    private const OPTION_SYNTAX_QUESTION_MARK = 'question_mark';

    public function getDefinition(): FixerDefinitionInterface
    {
        return new FixerDefinition(
            'Nullable PHPDoc type declarations should be standardised using the configured syntax.',
            [
                new CodeSample(
                    <<<'PHP'
                        <?php
                        /** @var null|int $value */
                        /** @param null|\Closure $callable */
                        /** @return int|null */

                        PHP
                ),
                new CodeSample(
                    <<<'PHP'
                        <?php
                        /** @var ?int $value */
                        /** @param ?\stdClass $obj */
                        /** @return ?int */

                        PHP,
                    ['syntax' => self::OPTION_SYNTAX_UNION]
                ),
            ]
        );
    }

    /**
     * {@inheritdoc}
     *
     * Must run before PhpdocAlignFixer, PhpdocTypesOrderFixer.
     * Must run after AlignMultilineCommentFixer, CommentToPhpdocFixer, PhpdocIndentFixer, PhpdocScalarFixer, PhpdocToCommentFixer, PhpdocTypesFixer.
     */
    public function getPriority(): int
    {
        return 1;
    }

    public function isCandidate(Tokens $tokens): bool
    {
        return $tokens->isTokenKindFound(\T_DOC_COMMENT);
    }

    protected function createConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder('syntax', 'Whether to use question mark (`?`) or explicit `null` union for nullable type.'))
                ->setAllowedValues([self::OPTION_SYNTAX_UNION, self::OPTION_SYNTAX_QUESTION_MARK])
                ->setDefault(self::OPTION_SYNTAX_QUESTION_MARK)
                ->getOption(),
        ]);
    }

    protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
    {
        foreach ($tokens as $index => $token) {
            if (!$token->isGivenKind(\T_DOC_COMMENT)) {
                continue;
            }

            $doc = new DocBlock($token->getContent());
            $annotations = $doc->getAnnotationsOfType(Annotation::TAGS_WITH_TYPES);

            if (0 === \count($annotations)) {
                continue;
            }

            foreach ($annotations as $annotation) {
                $typeExpression = $annotation->getTypeExpression();

                if (null === $typeExpression) {
                    continue;
                }

                $newTypes = $this->normalizeTypes($typeExpression);

                if (null !== $newTypes) {
                    $annotation->setTypes($newTypes);
                }
            }

            $newContent = $doc->getContent();

            if ($newContent !== $token->getContent()) {
                $tokens[$index] = new Token([\T_DOC_COMMENT, $newContent]);
            }
        }
    }

    /**
     * @return null|list<string>
     */
    private function normalizeTypes(TypeExpression $typeExpression): ?array
    {
        $isQuestionMarkSyntax = self::OPTION_SYNTAX_QUESTION_MARK === $this->configuration['syntax'];

        $changed = false;
        $newTypeExpression = $typeExpression->mapTypes(function (TypeExpression $type) use ($isQuestionMarkSyntax, &$changed): TypeExpression {
            $value = $type->toString();

            if ($isQuestionMarkSyntax) {
                // Convert `null|Type` or `Type|null` to `?Type`
                $newValue = $this->convertToQuestionMarkSyntax($value);
            } else {
                // Convert `?Type` to `null|Type`
                $newValue = $this->convertToUnionSyntax($value);
            }

            if ($newValue !== $value) {
                $changed = true;

                return new TypeExpression($newValue, null, []);
            }

            return $type;
        });

        if (!$changed) {
            return null;
        }

        return $newTypeExpression->getTypes();
    }

    private function convertToQuestionMarkSyntax(string $type): string
    {
        // Already using question mark syntax
        if (str_starts_with($type, '?')) {
            return $type;
        }

        // Not a union type
        if (!str_contains($type, '|')) {
            return $type;
        }

        // Skip intersection types (DNF)
        if (str_contains($type, '&')) {
            return $type;
        }

        // Check if this is a simple `null|Type` or `Type|null` union
        if (!Preg::match('/^(null\|(.+)|(.+)\|null)$/i', $type, $matches)) {
            return $type;
        }

        $nonNullType = $matches[2] !== '' ? $matches[2] : $matches[3];

        // Skip if the non-null part contains more unions (e.g., `null|int|string`)
        if (str_contains($nonNullType, '|')) {
            return $type;
        }

        // Skip if type is just `null`
        if ('null' === strtolower($nonNullType)) {
            return $type;
        }

        // Skip class constant references (e.g., `Foo::BAR`) - can't use `?` syntax with them
        if (str_contains($nonNullType, '::')) {
            return $type;
        }

        return '?'.$nonNullType;
    }

    private function convertToUnionSyntax(string $type): string
    {
        // Not using question mark syntax
        if (!str_starts_with($type, '?')) {
            return $type;
        }

        $innerType = substr($type, 1);

        // Skip if already contains union (shouldn't happen with valid PHPDoc, but be safe)
        if (str_contains($innerType, '|')) {
            return $type;
        }

        return 'null|'.$innerType;
    }
}

