<?php

declare(strict_types=1);

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace PhpCsFixer\Fixer\Phpdoc;

use PhpCsFixer\AbstractPhpdocTypesFixer;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\ConfigurableFixerTrait;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\FixerDefinition\FixerDefinitionInterface;
use PhpCsFixer\Preg;

/**
 * @phpstan-type _AutogeneratedInputConfiguration array{
 *  syntax?: 'question_mark'|'union',
 * }
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 *  syntax: 'question_mark'|'union',
 * }
 *
 * @implements ConfigurableFixerInterface<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration>
 *
 * @no-named-arguments Parameter names are not covered by the backward compatibility promise.
 */
final class PhpdocNullableTypeDeclarationFixer extends AbstractPhpdocTypesFixer implements ConfigurableFixerInterface
{
    /** @use ConfigurableFixerTrait<_AutogeneratedInputConfiguration, _AutogeneratedComputedConfiguration> */
    use ConfigurableFixerTrait;

    private const OPTION_SYNTAX_UNION = 'union';
    private const OPTION_SYNTAX_QUESTION_MARK = 'question_mark';

    public function getDefinition(): FixerDefinitionInterface
    {
        return new FixerDefinition(
            'Nullable PHPDoc type declarations should be standardised using the configured syntax.',
            [
                new CodeSample(
                    <<<'PHP'
                        <?php
                        /** @var null|int $value */
                        /** @param null|\Closure $callable */
                        /** @return int|null */

                        PHP
                ),
                new CodeSample(
                    <<<'PHP'
                        <?php
                        /** @var ?int $value */
                        /** @param ?\stdClass $obj */
                        /** @return ?int */

                        PHP,
                    ['syntax' => self::OPTION_SYNTAX_UNION]
                ),
            ]
        );
    }

    protected function createConfigurationDefinition(): FixerConfigurationResolverInterface
    {
        return new FixerConfigurationResolver([
            (new FixerOptionBuilder('syntax', 'Whether to use question mark (`?`) or explicit `null` union for nullable type.'))
                ->setAllowedValues([self::OPTION_SYNTAX_UNION, self::OPTION_SYNTAX_QUESTION_MARK])
                ->setDefault(self::OPTION_SYNTAX_QUESTION_MARK)
                ->getOption(),
        ]);
    }

    private function convertToQuestionMarkSyntax(string $type): string
    {
        // Already using question mark syntax
        if (str_starts_with($type, '?')) {
            return $type;
        }

        // Not a union type
        if (!str_contains($type, '|')) {
            return $type;
        }

        // Skip intersection types (DNF)
        if (str_contains($type, '&')) {
            return $type;
        }

        // Check if this is a simple `null|Type` or `Type|null` union
        if (!Preg::match('/^(null\|(.+)|(.+)\|null)$/i', $type, $matches)) {
            return $type;
        }

        $nonNullType = '' !== $matches[2] ? $matches[2] : $matches[3];

        // Skip if the non-null part contains more unions (e.g., `null|int|string`)
        if (str_contains($nonNullType, '|')) {
            return $type;
        }

        // Skip if type is just `null`
        if ('null' === strtolower($nonNullType)) {
            return $type;
        }

        // Skip class constant references (e.g., `Foo::BAR`) - can't use `?` syntax with them
        if (str_contains($nonNullType, '::')) {
            return $type;
        }

        return '?'.$nonNullType;
    }

    private function convertToUnionSyntax(string $type): string
    {
        // Not using question mark syntax
        if (!str_starts_with($type, '?')) {
            return $type;
        }

        $innerType = substr($type, 1);

        // Skip if already contains union (shouldn't happen with valid PHPDoc, but be safe)
        if (str_contains($innerType, '|')) {
            return $type;
        }

        return 'null|'.$innerType;
    }

    /**
     * @inheritDoc
     */
    protected function normalize(string $type): string
    {
        $isQuestionMarkSyntax = self::OPTION_SYNTAX_QUESTION_MARK === $this->configuration['syntax'];
        if ($isQuestionMarkSyntax) {
            return $this->convertToQuestionMarkSyntax($type);
        } else {
            return $this->convertToUnionSyntax($type);
        }
    }
}
